package com.app.controller;

import com.app.domain.Message;
import com.app.domain.User;
import com.app.repos.MessageRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.Set;

@Controller
public class MessageController {
    @Autowired  /*This means to get the bean called messageRepo, Which is auto-generated by Spring, we will use it to handle the data*/
    private MessageRepo messageRepo;

    MainController mainController = new MainController();

    @GetMapping("/user-messages/{user}")
    public String userMessages(
            @AuthenticationPrincipal User currentUser,/*принимает текущего пользователя, берем его из сессии*/
            @PathVariable User user,/*спринг вольмет переменную {user} и положит ее в user, так работает т.к. переменные одиникого называются*/
            Model model,
            @RequestParam(required = false) Message message /*(required = false) означает, что message не обязателен*/
    ) {
        Set<Message> messages = user.getMessages();

        model.addAttribute("messages", messages);
        model.addAttribute("message", message);
        model.addAttribute("isCurrentUser", currentUser.equals(user));

        return "userMessages";
    }

    @PostMapping("/user-messages/{user}")
    public String updateMessage(
            @AuthenticationPrincipal User currentUser,
            @PathVariable Long user,
            @RequestParam("id") Message message,
            @RequestParam("text") String text,
            @RequestParam("tag") String tag,
            @RequestParam("file") MultipartFile file
    ) throws IOException {
        if (message.getAuthor().equals(currentUser)) { //пользователь может менять только свои сообщения
            if (!StringUtils.isEmpty(text)) {
                message.setText(text); //обновляем текст, если не пусто
            }

            if (!StringUtils.isEmpty(tag)) {
                message.setTag(tag); //обновляем тэг, если не пусто
            }
            mainController.saveFile(message, file);
            messageRepo.save(message);
        }

        return "redirect:/user-messages/" + user;
    }
}
